[devops_vm]
# Obtener IP de: terraform output devops_vm_external_ip
devops-vm ansible_host=34.73.71.30 ansible_user=esteban

[devops_vm:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa_gcp
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Variables globales
[all:vars]
# Registry configuration
registry_url=us-central1-docker.pkg.dev/certain-perigee-459722-b4/ecommerce-microservices
gcp_project_id=certain-perigee-459722-b4

# Kubernetes clusters
dev_cluster_endpoint=REPLACE_WITH_DEV_ENDPOINT
stage_cluster_endpoint=REPLACE_WITH_STAGE_ENDPOINT  
prod_cluster_endpoint=REPLACE_WITH_PROD_ENDPOINT
